language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
addon:
    apt:
        packages:
            - python-qt4

before_install:
    - pip install --no-index --trusted-host travis-wheels.scikit-image.org --find-links=http://travis-wheels.scikit-image.org numpy scipy matplotlib PySide
    - pip install colorspacious
    - pip install pytest pytest-cov
    - python $(dirname $(which python))/pyside_postinstall.py -install
    - sh -e  /etc/init.d/xvfb start
    - export DISPLAY=:99
script:
    - "py.test tests.py" 
sudo: false